services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - tailscale-traffic-manager-net
  ignition_subscriber:
    image: iedgir01/traffic_manager_ignition_subscriber:latest
    container_name: ignition_subscriber
    restart: unless-stopped
    depends_on:
      - postgres_db
    environment:
      PYTHONUNBUFFERED: 1
      MQTT_BROKER: ${MQTT_BROKER}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_TOPIC: ${MQTT_TOPIC}
      GOTIFY_URL: ${GOTIFY_URL}
      GOTIFY_TOKEN: ${GOTIFY_TOKEN}
      GOTIFY_PRIORITY: ${GOTIFY_PRIORITY}
      IGNITION_TIMEOUT: ${IGNITION_TIMEOUT}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}
      CLAUDE_SUMMARY_STYLE: ${CLAUDE_SUMMARY_STYLE}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      DATA_DIR: ${DATA_DIR}
      MAPS_DIR: ${MAPS_DIR}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/app/data
    networks:
      - tailscale-traffic-manager-net

  discord_bot:
    image: iedgir01/traffic_manager_discord_bot:latest
    container_name: discord_bot
    restart: unless-stopped
    depends_on:
      - postgres_db
    environment:
      PYTHONUNBUFFERED: 1
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      GOTIFY_URL: ${GOTIFY_URL}
      GOTIFY_TOKEN: ${GOTIFY_TOKEN}
      GOTIFY_PRIORITY: ${GOTIFY_PRIORITY}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      DATA_DIR: ${DATA_DIR}
      MAPS_DIR: ${MAPS_DIR}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/app/data
    networks:
      - tailscale-traffic-manager-net

networks:
  tailscale-traffic-manager-net:
    driver: bridge
