services:
  ignition_subscriber:
    image: iedgir01/traffic_manager_ignition_subscriber:latest
    container_name: ignition_subscriber
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
      MQTT_BROKER: ${MQTT_BROKER}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_TOPIC: ${MQTT_TOPIC}
      GOTIFY_URL: ${GOTIFY_URL}
      GOTIFY_TOKEN: ${GOTIFY_TOKEN}
      GOTIFY_PRIORITY: ${GOTIFY_PRIORITY}
      IGNITION_TIMEOUT: ${IGNITION_TIMEOUT}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      DATA_DIR: ${DATA_DIR}
      MAPS_DIR: ${MAPS_DIR}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /data/docker/traffic_manager:/app/data
    networks:
      - docker-bridge

  discord_bot:
    image: iedgir01/traffic_manager_discord_bot:latest
    container_name: discord_bot
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      GOTIFY_URL: ${GOTIFY_URL}
      GOTIFY_TOKEN: ${GOTIFY_TOKEN}
      GOTIFY_PRIORITY: ${GOTIFY_PRIORITY}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      DATA_DIR: ${DATA_DIR}
      MAPS_DIR: ${MAPS_DIR}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /data/docker/traffic_manager:/app/data
    networks:
      - docker-bridge

networks:
  docker-bridge:
    external: true
