services:
  ignition_subscriber:
    image: iedgir01/traffic_manager_ignition_subscriber:latest
    container_name: ignition_subscriber
    restart: unless-stopped
    command: ["python", "-u", "-m", "ignition_subscriber/subscriber.py"]
    environment:
      PYTHONUNBUFFERED: 1
      MQTT_BROKER: YOUR_MQTT_BROKER
      MQTT_PORT: YOUR_MQTT_PORT
      MQTT_TOPIC: YOUR_MQTT_TOPIC
      IGNITION_TIMEOUT: 60
      DISCORD_WEBHOOK_URL: YOUR_DISCORD_WEBHOOK_URL
      GOOGLE_MAPS_API_KEY: YOUR_GOOGLE_MAPS_API_KEY
      DATA_DIR: /app/data
      MAPS_DIR: /app/data/maps
      DB_PATH: /app/data/traffic_routes.db
    volumes:
      - ./data:/app/data
    networks:
      - tailscale-traffic-manager-net

  discord_bot:
    image: iedgir01/traffic_manager_discord_bot:latest
    container_name: discord_bot
    restart: unless-stopped
    command: ["python", "-u", "-m", "discord_bot/traffic_helper.py"]
    environment:
      PYTHONUNBUFFERED: 1
      DISCORD_BOT_TOKEN: YOUR_DISCORD_BOT_TOKEN
      GOOGLE_MAPS_API_KEY: YOUR_GOOGLE_MAPS_API_KEY
      DATA_DIR: /app/data
      MAPS_DIR: /app/data/maps
      DB_PATH: /app/data/traffic_routes.db
    volumes:
      - ./data:/app/data
    networks:
      - tailscale-traffic-manager-net

networks:
  tailscale-traffic-manager-net:
    driver: bridge