services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: YOUR_POSTGRES_USER
      POSTGRES_PASSWORD: YOUR_POSTGRES_PASSWORD
      POSTGRES_DB: YOUR_POSTGRES_DB
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - tailscale-traffic-manager-net
  ignition_subscriber:
    image: iedgir01/traffic_manager_ignition_subscriber:latest
    container_name: ignition_subscriber
    restart: unless-stopped
    depends_on:
      - postgres_db
    environment:
      PYTHONUNBUFFERED: 1
      MQTT_BROKER: YOUR_MQTT_BROKER
      MQTT_PORT: YOUR_MQTT_PORT
      MQTT_TOPIC: YOUR_MQTT_TOPIC
      GOTIFY_URL: YOUR_GOTIFY_URL
      GOTIFY_TOKEN: YOUR_GOTIFY_TOKEN
      GOTIFY_PRIORITY: 5
      IGNITION_TIMEOUT: 60
      DISCORD_WEBHOOK_URL: YOUR_DISCORD_WEBHOOK_URL
      CLAUDE_API_KEY: YOUR_CLAUDE_API_KEY
      CLAUDE_SUMMARY_STYLE: >
        Generate a traffic summary in a random conversational style.
        Choose from: Professional, Local News Reporter, Sarcastic,
        Friendly Casual, Trump-Style, Morgan Freeman Narrator,
        Epic Adventure, or Fairy Tale.
        Make it engaging for TTS and avoid paragraph format.
      GOOGLE_MAPS_API_KEY: YOUR_GOOGLE_MAPS_API_KEY
      DATA_DIR: /app/data
      MAPS_DIR: /app/data/maps
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: YOUR_POSTGRES_USER
      POSTGRES_PASSWORD: YOUR_POSTGRES_PASSWORD
      POSTGRES_DB: YOUR_POSTGRES_DB
    volumes:
      - ./data:/app/data
    networks:
      - tailscale-traffic-manager-net

  discord_bot:
    image: iedgir01/traffic_manager_discord_bot:latest
    container_name: discord_bot
    restart: unless-stopped
    depends_on:
      - postgres_db
    environment:
      PYTHONUNBUFFERED: 1
      DISCORD_BOT_TOKEN: YOUR_DISCORD_BOT_TOKEN
      DISCORD_WEBHOOK_URL: YOUR_DISCORD_WEBHOOK_URL
      GOTIFY_URL: YOUR_GOTIFY_URL
      GOTIFY_TOKEN: YOUR_GOTIFY_TOKEN
      GOTIFY_PRIORITY: 5
      GOOGLE_MAPS_API_KEY: YOUR_GOOGLE_MAPS_API_KEY
      DATA_DIR: /app/data
      MAPS_DIR: /app/data/maps
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: YOUR_POSTGRES_USER
      POSTGRES_PASSWORD: YOUR_POSTGRES_PASSWORD
      POSTGRES_DB: YOUR_POSTGRES_DB
    volumes:
      - ./data:/app/data
    networks:
      - tailscale-traffic-manager-net

networks:
  tailscale-traffic-manager-net:
    driver: bridge