services:
  traffic_manager:
    build: .
    container_name: traffic_manager
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
      MQTT_BROKER: YOUR_MQTT_BROKER
      MQTT_PORT: YOUR_MQTT_PORT
      MQTT_TOPIC: YOUR_MQTT_TOPIC
      IGNITION_TIMEOUT: 60
      DISCORD_BOT_TOKEN: YOUR_DISCORD_BOT_TOKEN
      DISCORD_WEBHOOK_URL: YOUR_DISCORD_WEBHOOK_URL
      GOOGLE_MAPS_API_KEY: YOUR_GOOGLE_MAPS_API_KEY
      DATA_DIR: /app/data
      MAPS_DIR: /app/data/maps
      DB_PATH: /app/data/traffic_routes.db
    volumes:
      - ./data:/app/data
    tty: true
    stdin_open: true
    networks:
      - tailscale-traffic-manager-net

networks:
  tailscale-traffic-manager-net:
    driver: bridge